export const products = [
  {
    id: 0,
    cat: "Waffle",
    name: "Waffle with Berries",
    price: 6.5,
    imageSp: "image-waffle-mobile.jpg",
    imageTb: "image-waffle-tablet.jpg",
    imagePc: "image-waffle-desktop.jpg",
  },
  {
    id: 1,
    cat: "Crème Brûlée",
    name: "Vanilla Bean Crème Brûlée",
    price: 7.0,
    imageSp: "image-creme-brulee-mobile.jpg",
    imageTb: "image-creme-brulee-tablet.jpg",
    imagePc: "image-creme-brulee-desktop.jpg",
  },
  {
    id: 2,
    cat: "Macaron",
    name: "Macaron Mix of Five",
    price: 8.0,
    imageSp: "image-macaron-mobile.jpg",
    imageTb: "image-macaron-tablet.jpg",
    imagePc: "image-macaron-desktop.jpg",
  },
  {
    id: 3,
    cat: "Tiramisu",
    name: "Classic Tiramisu",
    price: 5.5,
    imageSp: "image-tiramisu-mobile.jpg",
    imageTb: "image-tiramisu-tablet.jpg",
    imagePc: "image-tiramisu-desktop.jpg",
  },
  {
    id: 4,
    cat: "Baklava",
    name: "Pistachio Baklava",
    price: 4.0,
    imageSp: "image-baklava-mobile.jpg",
    imageTb: "image-baklava-tablet.jpg",
    imagePc: "image-baklava-desktop.jpg",
  },
  {
    id: 5,
    cat: "Pie",
    name: "Lemon Meringue Pie",
    price: 5.0,
    imageSp: "image-meringue-mobile.jpg",
    imageTb: "image-meringue-tablet.jpg",
    imagePc: "image-meringue-desktop.jpg",
  },
  {
    id: 6,
    cat: "Cake",
    name: "Red Velvet Cake",
    price: 4.5,
    imageSp: "image-cake-mobile.jpg",
    imageTb: "image-cake-tablet.jpg",
    imagePc: "image-cake-desktop.jpg",
  },
  {
    id: 7,
    cat: "Brownie",
    name: "Salted Caramel Brownie",
    price: 4.5,
    imageSp: "image-brownie-mobile.jpg",
    imageTb: "image-brownie-tablet.jpg",
    imagePc: "image-brownie-desktop.jpg",
  },
  {
    id: 8,
    cat: "Panna Cotta",
    name: "Vanilla Panna Cotta",
    price: 6.5,
    imageSp: "image-panna-cotta-mobile.jpg",
    imageTb: "image-panna-cotta-tablet.jpg",
    imagePc: "image-panna-cotta-desktop.jpg",
  },
];
